### ISSUE TITLE
Modulefile - Self Reference?

### ISSUE THREAD

**Issue by pjfoley** [stdmod/stdmod#2]
Hi,

I am just starting to look at writing my modules and was looking for a module skeleton layout and while searching came across this one.

Looking in the Modulefile to see what dependancies would be pulled in I noticed that it seems to self reference?

https://github.com/stdmod/stdmod/blob/master/Modulefile#L10

I am not sure if this is by design?

Thanks,

Peter.

**Comment by alvagante** [comment]
You are right. Fixed.
